name: Update README with Latest Activity

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: readme-bot/actions@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
